runtime: nodejs
env: flex
env_variables:
    MONGO_URL: mongodb://localhost/IMS
    MONGO_URL_TEST: mongodb://localhost/IMSTEST
    MONGO_URL_PROD: "mongodb+srv://haritha99:YBEkBvo3eKX1JpfE@cluster0.lgdv5i2.mongodb.net/?retryWrites=true&w=majority"
    SERVER_PORT: 8080
