steps:
    - name: "gcr.io/cloud-builders/npm"
      dir: "/workspace/src"
      args: ["cache", "clean", "--force"]

    - name: "gcr.io/cloud-builders/npm"
      dir: "/workspace/src"
      args: ["install", "-g", "npm"]

    - name: "gcr.io/cloud-builders/npm"
      dir: "/workspace/src"
      args: ["install", ".", "--loglevel=verbose"]

    - name: "gcr.io/cloud-builders/npm"
      dir: "/workspace/src"
      args: ["run", "--loglevel=verbose"]

    - name: "gcr.io/cloud-builders/gcloud"
      dir: "/workspace/src/Crimewatch-Backend"
      args: ["app", "deploy", "--project", "crime-watch-375407"]
