steps:
    - name: "gcr.io/cloud-builders/npm"
      args: ["cache", "clean", "--force"]

    - name: "gcr.io/cloud-builders/npm"
      args: ["install", "-g", "npm"]

    - name: "gcr.io/cloud-builders/npm"
      args: ["update", "--loglevel=verbose"]

    - name: "gcr.io/cloud-builders/npm"
      entrypoint: "bash"
      args:
          - "-c"
          - |
              cd ../
              npm install . --legacy-peer-deps --loglevel=verbose

    - name: "gcr.io/cloud-builders/npm"
      args: ["run"]
