steps:
    - name: "gcr.io/cloud-builders/npm"
      dir: "/workspace/src"
      args: ["install", ".", "--loglevel=verbose"]

    # - name: "gcr.io/cloud-builders/npm"
    #   dir: "/workspace/src"
    #   args: ["test", "--loglevel=verbose"]

    # - name: "gcr.io/cloud-builders/npm"
    #   dir: "/workspace/src"
    #   args: ["run", "--loglevel=verbose"]

    - name: "gcr.io/cloud-builders/npm"
      dir: "/workspace/src/Crimewatch-Frontend"
      args: ["start", "--loglevel=verbose"]

    - name: "gcr.io/cloud-builders/gcloud"
      dir: "/workspace/src"
      args: ["app", "deploy", "--project", "crime-watch-375407"]
