steps:
    - name: "gcr.io/cloud-builders/npm"
      entrypoint: "bash"
      args:
          - "-c"
          - |
              cd ../
              npm install .

    - name: "gcr.io/cloud-builders/npm"
      args: ["run"]
