steps:
    - name: "gcr.io/cloud-builders/npm"
      args: ["cache", "clean", "--force"]
      
    - name: "gcr.io/cloud-builders/npm"
      entrypoint: "bash"
      args:
          - "-c"
          - |
              cd ../
              npm install . --loglevel=verbose

    - name: "gcr.io/cloud-builders/npm"
      args: ["run"]
